### ISSUE TITLE
Classification example on multi token field

### ISSUE THREAD

**Issue by umitkose** [bakdata/dedupe#11]
I have a question. On your examples person name has been splitted as first and lastname. In real life data may be presented on just one field. Also it's common two have multiple words last names. So it's not easy to split data like first one is first name and second is last name. 
I tried myself but could not figure it out yet. I guess I should use MongeElkan similarity measurement but do not know how to do it.
Would it be possible to extend your example with a multi token field?

**Comment by AHeise** [comment]
Hi @umitkose ,

the general idea is right. You can use the words() tokenization and receive a list of words.

Monge Elkan is not the best fit, however. Elements can be matched more than once and that makes John Johnson and John Smith a likely match.

But there was no good compound similarity measure implemented yet. So I added stableMatching based on https://en.wikipedia.org/wiki/Stable_marriage_problem . Now, every part of the name will be used at most once.

I'm currently in quite a bit of polishing, which also includes some refactoring. To avoid too much switching forth and back, I added an example in the working branch:
https://github.com/bakdata/dedupe/blob/refactor_common/examples/src/main/java/com/bakdata/dedupe/person/PersonClassifierWithMultipleNames.java
I also added some comments about which cases are addressed. If you have more questions, feel free to ask.

I will merge into master as soon as #10 was approved. Since we got some incompatible changes, the new version will be 2.0.0.

**Comment by umitkose** [comment]
Thank you very much for fast reply.I try and gide feedback.
